name: Test

on: [push]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-haskell@v1.1.3
      with:
        ghc-version: '8.6.5'
        enable-stack: true
        stack-version: 'latest'
    - name: Build
      run: stack build
    - name: Test
      run: stack test
