name: Test
on: [push]
jobs:
  test-on-ubuntu:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-haskell@v1.1.3
      with:
        ghc-version: '8.6.5'
        enable-stack: true
        stack-version: 'latest'
    - name: Install z3
      run: sudo apt-get install z3
    - name: Build
      run: stack build
    - name: Test
      run: stack test
  test-on-macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-haskell@v1.1.3
      with:
        ghc-version: '8.6.5'
        enable-stack: true
        stack-version: 'latest'
    - name: Install z3
      run: brew install z3
    - name: Build
      run: stack build
    - name: Test
      run: stack test
